<a href="https://colab.research.google.com/github/fathimathulmizna632-art/ai_hire/blob/main/Day13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [ ]:
#transpose
b=np.array([[1,2,3],[4,5,6]])
np.transpose(b)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# another way to transpose
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#flatten
#it copy and collapse into 1 d array
a=np.array([[1,2,3],[3,4,5]])
print(a)
b=a.flatten()
b

[[1 2 3]
 [3 4 5]]


array([1, 2, 3, 3, 4, 5])

In [ ]:
b[1]=23
print("a=",a)
print("b=",b)

a= [[1 2 3]
 [3 4 5]]
b= [ 1 23  3  3  4  5]


In [ ]:
#ravel()
#it gives a view rather than cpy changes made seen in og
a=np.array([[1,2,3],[3,4,5]])
print(a)
b=a.ravel()
print(b)
b[1]=99
print(a)
print(b)

[[1 2 3]
 [3 4 5]]
[1 2 3 3 4 5]
[[ 1 99  3]
 [ 3  4  5]]
[ 1 99  3  3  4  5]


In [ ]:
#reshape
# change the size of an array


In [ ]:
#resize
#repeat or if not needed it trucate or delete
a=np.array([1,2,3,4,5,6])
np.resize(a,(2,3))


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.resize(a,(3,4))

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [ ]:
#np.vstack(vertical stack)
#stacks array vertically


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
ver=np.vstack((a,b))
print(ver)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#np.hstack(horizontal stack)
hor=np.hstack((a,b))
print(hor)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#arithmetic op on array elements
a=np.array([[1,2,3],[4,5,6]])
#scalar op
a+2

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [ ]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
a%2

array([[1, 0, 1],
       [0, 1, 0]])

In [ ]:
a/5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [ ]:
a//10

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a**5

array([[   1,   32,  243],
       [1024, 3125, 7776]])

In [ ]:
#scalar comparison
new=np.array([12,2,3,5])


In [ ]:
new>=5

array([ True, False, False,  True])

In [ ]:
new<=4

array([False,  True,  True, False])

In [ ]:
new==3

array([False, False,  True, False])

In [ ]:
new>2

array([ True, False,  True,  True])

In [ ]:
new<2

array([False, False, False, False])

In [ ]:
#logical operators


In [ ]:
a=np.array([10,20,30,40])
print(np.logical_and(a>15,a<35))
print(np.logical_or(a>15,a<35))
print(np.logical_not(a>25))

[False  True  True False]
[ True  True  True  True]
[ True  True False False]


In [ ]:
#statistical op
array=np.array([[1,2,3],[5,6,7],[7,8,9]])
array


array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [ ]:
#max()
np.max(array)

np.int64(9)

In [ ]:
np.max(array,axis=0)

array([7, 8, 9])

In [ ]:
np.max(array,axis=1)

array([3, 7, 9])

In [ ]:
#min()
np.min(array)

np.int64(1)

In [ ]:
np.min(array,axis=0)

array([1, 2, 3])

In [ ]:
np.min(array,axis=1)

array([1, 5, 7])

In [ ]:
a=np.array([1,2,3,4,5,6,78])
print(np.mean(a))
print(np.median(a))
print(np.sum(a))

14.142857142857142
4.0
99


In [ ]:
#inserting elements
arr1=np.arange(6,12)
arr1

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
#syntax==np.insert(arrayname,position,element)
a=np.insert(arr1,3,100)
a

array([  6,   7,   8, 100,   9,  10,  11])

In [ ]:
#adding in 2d and more array
a=np.full([3,3,],5)
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
arr=np.insert(a,2,125,axis=0)
arr

array([[  5,   5,   5],
       [  5,   5,   5],
       [125, 125, 125],
       [  5,   5,   5]])

In [ ]:
arr=np.insert(a,2,125,axis=1)
arr

array([[  5,   5, 125,   5],
       [  5,   5, 125,   5],
       [  5,   5, 125,   5]])

In [ ]:
np.insert(a,2,[100,125,100,125,300],axis=1)

array([[  5,   1, 100,   7,   2,   6],
       [  1,   8, 125,   6,   6,   2],
       [  8,   7, 100,   8,   3,   2],
       [  6,   3, 125,   9,   8,   1],
       [  6,   5, 300,   9,   4,   3]])

In [ ]:
#delete an element
np.delete(a,0)

array([1, 7, 2, 6, 1, 8, 6, 6, 2, 8, 7, 8, 3, 2, 6, 3, 9, 8, 1, 6, 5, 9,
       4, 3])

In [ ]:
#delete a row or coloumn
arr4=np.array([[1,1,6],[7,2,8]])
print(arr4)


[[1 1 6]
 [7 2 8]]


array([[1, 1, 6]])

In [ ]:
np.delete(arr4,1,axis=1)

array([[1, 6],
       [7, 8]])

In [ ]:
#to delete more then 1 row or column
a=np.random.randint(1,10,(5,5))
a

array([[5, 1, 7, 2, 6],
       [1, 8, 6, 6, 2],
       [8, 7, 8, 3, 2],
       [6, 3, 9, 8, 1],
       [6, 5, 9, 4, 3]])

In [ ]:
np.delete(a,(0,1,3),axis=1)

array([[7, 6],
       [6, 2],
       [8, 2],
       [9, 1],
       [9, 3]])

In [ ]:
np.delete(a,(0,2,3),axis=1)

array([[1, 6],
       [8, 2],
       [7, 2],
       [3, 1],
       [5, 3]])

In [ ]:
#sort
np.sort(a)

array([[1, 2, 5, 6, 7],
       [1, 2, 6, 6, 8],
       [2, 3, 7, 8, 8],
       [1, 3, 6, 8, 9],
       [3, 4, 5, 6, 9]])

In [ ]:
#split
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#split(arrayname,index)
np.split(ar,[2])


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [ ]:
#split(arrayname,npo.of split,axis)
np.split(ar,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
np.split(ar,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [ ]:
#horizontal split

np.hsplit(ar,[2])

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [ ]:
#hsplit(arrayname,no of split)
np.hsplit(ar,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [ ]:
#same for hsplit
np.vsplit(ar,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [ ]:
#concatenate
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
np.concatenate((c,d),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a=np.arange(10,51,10)
a

array([10, 20, 30, 40, 50])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [ ]:
c=np.arange(1,13)
print(c)
c.reshape(3,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a=np.full([2,3],5)
print(a)
a.resize(3,)
print(a)

[[5 5 5]
 [5 5 5]]
[5 5 5]


In [ ]:
arr=np.array([[10,20],[30,40]])
arr
print(np.insert(arr,4,35))
print(np.insert(arr,3,[60,70]))
print(np.insert(arr,2,10))
print(np.insert(arr,2,20))
print(np.insert(arr,2,30))
print(np.insert(arr,2,5))
print(np.insert(arr,2,15))
print(np.insert(arr,2,10))

[10 20 30 40 35]
[10 20 30 60 70 40]
[10 20 10 30 40]
[10 20 20 30 40]
[10 20 30 30 40]
[10 20  5 30 40]
[10 20 15 30 40]
[10 20 10 30 40]


In [ ]:
a=np.array([1,2,3,4])
print(a+10)

[11 12 13 14]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
np.insert(a,2,[7,8,9],axis=0)

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.array([[2,3,4],[5,6,7]]
             a=np.append()